module main

struct CPUInstruction {
	disassembly string
	bytes       u8
	immediate   bool
	function    ?fn (mut cpu CPU, data []u8)
}

fn inst_nop(mut cpu CPU, _ []u8) {
	cpu.clocks += 4
}

fn inst_ld_hl_n16(mut cpu CPU, data []u8) {
	cpu.routine_ld_16(data, mut &cpu.r.hl.half.hi, mut &cpu.r.hl.half.lo)
}

fn inst_xor_a_a(mut cpu CPU, _ []u8) {
	unsafe {
		cpu.r.af.full = 0
	}
	cpu.set_flag_subtract(false)
	cpu.set_flag_carry(false)
	cpu.set_flag_half_carry(false)
	cpu.set_flag_zero(true)
	cpu.clocks += 4
}

fn inst_jp_a16(mut cpu CPU, data []u8) {
	cpu.clocks += 4
	mut tmp := u32(memory_bus_read(data, unsafe {cpu.r.pc.full}))
	cpu.pc_inc()
	cpu.clocks += 4
	tmp |= u32(memory_bus_read(data, unsafe {cpu.r.pc.full})) << 8
	cpu.pc_inc()
	cpu.clocks += 4
	cpu.r.pc.full = u16(tmp)
	cpu.clocks += 4
}

const insts_unprefixed = [
	CPUInstruction{'NOP', 1, true, inst_nop},
	CPUInstruction{'LD BC, n16', 3, true, none},
	CPUInstruction{'LD BC, A', 1, false, none},
	CPUInstruction{'INC BC', 1, true, none},
	CPUInstruction{'INC B', 1, true, none},
	CPUInstruction{'DEC B', 1, true, none},
	CPUInstruction{'LD B, n8', 2, true, none},
	CPUInstruction{'RLCA', 1, true, none},
	CPUInstruction{'LD a16, SP', 3, false, none},
	CPUInstruction{'ADD HL, BC', 1, true, none},
	CPUInstruction{'LD A, BC', 1, false, none},
	CPUInstruction{'DEC BC', 1, true, none},
	CPUInstruction{'INC C', 1, true, none},
	CPUInstruction{'DEC C', 1, true, none},
	CPUInstruction{'LD C, n8', 2, true, none},
	CPUInstruction{'RRCA', 1, true, none},
	CPUInstruction{'STOP', 2, true, none},
	CPUInstruction{'LD DE, n16', 3, true, none},
	CPUInstruction{'LD DE, A', 1, false, none},
	CPUInstruction{'INC DE', 1, true, none},
	CPUInstruction{'INC D', 1, true, none},
	CPUInstruction{'DEC D', 1, true, none},
	CPUInstruction{'LD D, n8', 2, true, none},
	CPUInstruction{'RLA', 1, true, none},
	CPUInstruction{'JR e8', 2, true, none},
	CPUInstruction{'ADD HL, DE', 1, true, none},
	CPUInstruction{'LD A, DE', 1, false, none},
	CPUInstruction{'DEC DE', 1, true, none},
	CPUInstruction{'INC E', 1, true, none},
	CPUInstruction{'DEC E', 1, true, none},
	CPUInstruction{'LD E, n8', 2, true, none},
	CPUInstruction{'RRA', 1, true, none},
	CPUInstruction{'JR NZ, e8', 2, true, none},
	CPUInstruction{'LD HL, n16', 3, true, inst_ld_hl_n16},
	CPUInstruction{'LD HL, A', 1, false, none},
	CPUInstruction{'INC HL', 1, true, none},
	CPUInstruction{'INC H', 1, true, none},
	CPUInstruction{'DEC H', 1, true, none},
	CPUInstruction{'LD H, n8', 2, true, none},
	CPUInstruction{'DAA', 1, true, none},
	CPUInstruction{'JR Z, e8', 2, true, none},
	CPUInstruction{'ADD HL, HL', 1, true, none},
	CPUInstruction{'LD A, HL', 1, false, none},
	CPUInstruction{'DEC HL', 1, true, none},
	CPUInstruction{'INC L', 1, true, none},
	CPUInstruction{'DEC L', 1, true, none},
	CPUInstruction{'LD L, n8', 2, true, none},
	CPUInstruction{'CPL', 1, true, none},
	CPUInstruction{'JR NC, e8', 2, true, none},
	CPUInstruction{'LD SP, n16', 3, true, none},
	CPUInstruction{'LD HL, A', 1, false, none},
	CPUInstruction{'INC SP', 1, true, none},
	CPUInstruction{'INC HL', 1, false, none},
	CPUInstruction{'DEC HL', 1, false, none},
	CPUInstruction{'LD HL, n8', 2, false, none},
	CPUInstruction{'SCF', 1, true, none},
	CPUInstruction{'JR C, e8', 2, true, none},
	CPUInstruction{'ADD HL, SP', 1, true, none},
	CPUInstruction{'LD A, HL', 1, false, none},
	CPUInstruction{'DEC SP', 1, true, none},
	CPUInstruction{'INC A', 1, true, none},
	CPUInstruction{'DEC A', 1, true, none},
	CPUInstruction{'LD A, n8', 2, true, none},
	CPUInstruction{'CCF', 1, true, none},
	CPUInstruction{'LD B, B', 1, true, none},
	CPUInstruction{'LD B, C', 1, true, none},
	CPUInstruction{'LD B, D', 1, true, none},
	CPUInstruction{'LD B, E', 1, true, none},
	CPUInstruction{'LD B, H', 1, true, none},
	CPUInstruction{'LD B, L', 1, true, none},
	CPUInstruction{'LD B, HL', 1, false, none},
	CPUInstruction{'LD B, A', 1, true, none},
	CPUInstruction{'LD C, B', 1, true, none},
	CPUInstruction{'LD C, C', 1, true, none},
	CPUInstruction{'LD C, D', 1, true, none},
	CPUInstruction{'LD C, E', 1, true, none},
	CPUInstruction{'LD C, H', 1, true, none},
	CPUInstruction{'LD C, L', 1, true, none},
	CPUInstruction{'LD C, HL', 1, false, none},
	CPUInstruction{'LD C, A', 1, true, none},
	CPUInstruction{'LD D, B', 1, true, none},
	CPUInstruction{'LD D, C', 1, true, none},
	CPUInstruction{'LD D, D', 1, true, none},
	CPUInstruction{'LD D, E', 1, true, none},
	CPUInstruction{'LD D, H', 1, true, none},
	CPUInstruction{'LD D, L', 1, true, none},
	CPUInstruction{'LD D, HL', 1, false, none},
	CPUInstruction{'LD D, A', 1, true, none},
	CPUInstruction{'LD E, B', 1, true, none},
	CPUInstruction{'LD E, C', 1, true, none},
	CPUInstruction{'LD E, D', 1, true, none},
	CPUInstruction{'LD E, E', 1, true, none},
	CPUInstruction{'LD E, H', 1, true, none},
	CPUInstruction{'LD E, L', 1, true, none},
	CPUInstruction{'LD E, HL', 1, false, none},
	CPUInstruction{'LD E, A', 1, true, none},
	CPUInstruction{'LD H, B', 1, true, none},
	CPUInstruction{'LD H, C', 1, true, none},
	CPUInstruction{'LD H, D', 1, true, none},
	CPUInstruction{'LD H, E', 1, true, none},
	CPUInstruction{'LD H, H', 1, true, none},
	CPUInstruction{'LD H, L', 1, true, none},
	CPUInstruction{'LD H, HL', 1, false, none},
	CPUInstruction{'LD H, A', 1, true, none},
	CPUInstruction{'LD L, B', 1, true, none},
	CPUInstruction{'LD L, C', 1, true, none},
	CPUInstruction{'LD L, D', 1, true, none},
	CPUInstruction{'LD L, E', 1, true, none},
	CPUInstruction{'LD L, H', 1, true, none},
	CPUInstruction{'LD L, L', 1, true, none},
	CPUInstruction{'LD L, HL', 1, false, none},
	CPUInstruction{'LD L, A', 1, true, none},
	CPUInstruction{'LD HL, B', 1, false, none},
	CPUInstruction{'LD HL, C', 1, false, none},
	CPUInstruction{'LD HL, D', 1, false, none},
	CPUInstruction{'LD HL, E', 1, false, none},
	CPUInstruction{'LD HL, H', 1, false, none},
	CPUInstruction{'LD HL, L', 1, false, none},
	CPUInstruction{'HALT', 1, true, none},
	CPUInstruction{'LD HL, A', 1, false, none},
	CPUInstruction{'LD A, B', 1, true, none},
	CPUInstruction{'LD A, C', 1, true, none},
	CPUInstruction{'LD A, D', 1, true, none},
	CPUInstruction{'LD A, E', 1, true, none},
	CPUInstruction{'LD A, H', 1, true, none},
	CPUInstruction{'LD A, L', 1, true, none},
	CPUInstruction{'LD A, HL', 1, false, none},
	CPUInstruction{'LD A, A', 1, true, none},
	CPUInstruction{'ADD A, B', 1, true, none},
	CPUInstruction{'ADD A, C', 1, true, none},
	CPUInstruction{'ADD A, D', 1, true, none},
	CPUInstruction{'ADD A, E', 1, true, none},
	CPUInstruction{'ADD A, H', 1, true, none},
	CPUInstruction{'ADD A, L', 1, true, none},
	CPUInstruction{'ADD A, HL', 1, false, none},
	CPUInstruction{'ADD A, A', 1, true, none},
	CPUInstruction{'ADC A, B', 1, true, none},
	CPUInstruction{'ADC A, C', 1, true, none},
	CPUInstruction{'ADC A, D', 1, true, none},
	CPUInstruction{'ADC A, E', 1, true, none},
	CPUInstruction{'ADC A, H', 1, true, none},
	CPUInstruction{'ADC A, L', 1, true, none},
	CPUInstruction{'ADC A, HL', 1, false, none},
	CPUInstruction{'ADC A, A', 1, true, none},
	CPUInstruction{'SUB A, B', 1, true, none},
	CPUInstruction{'SUB A, C', 1, true, none},
	CPUInstruction{'SUB A, D', 1, true, none},
	CPUInstruction{'SUB A, E', 1, true, none},
	CPUInstruction{'SUB A, H', 1, true, none},
	CPUInstruction{'SUB A, L', 1, true, none},
	CPUInstruction{'SUB A, HL', 1, false, none},
	CPUInstruction{'SUB A, A', 1, true, none},
	CPUInstruction{'SBC A, B', 1, true, none},
	CPUInstruction{'SBC A, C', 1, true, none},
	CPUInstruction{'SBC A, D', 1, true, none},
	CPUInstruction{'SBC A, E', 1, true, none},
	CPUInstruction{'SBC A, H', 1, true, none},
	CPUInstruction{'SBC A, L', 1, true, none},
	CPUInstruction{'SBC A, HL', 1, false, none},
	CPUInstruction{'SBC A, A', 1, true, none},
	CPUInstruction{'AND A, B', 1, true, none},
	CPUInstruction{'AND A, C', 1, true, none},
	CPUInstruction{'AND A, D', 1, true, none},
	CPUInstruction{'AND A, E', 1, true, none},
	CPUInstruction{'AND A, H', 1, true, none},
	CPUInstruction{'AND A, L', 1, true, none},
	CPUInstruction{'AND A, HL', 1, false, none},
	CPUInstruction{'AND A, A', 1, true, none},
	CPUInstruction{'XOR A, B', 1, true, none},
	CPUInstruction{'XOR A, C', 1, true, none},
	CPUInstruction{'XOR A, D', 1, true, none},
	CPUInstruction{'XOR A, E', 1, true, none},
	CPUInstruction{'XOR A, H', 1, true, none},
	CPUInstruction{'XOR A, L', 1, true, none},
	CPUInstruction{'XOR A, HL', 1, false, none},
	CPUInstruction{'XOR A, A', 1, true, inst_xor_a_a},
	CPUInstruction{'OR A, B', 1, true, none},
	CPUInstruction{'OR A, C', 1, true, none},
	CPUInstruction{'OR A, D', 1, true, none},
	CPUInstruction{'OR A, E', 1, true, none},
	CPUInstruction{'OR A, H', 1, true, none},
	CPUInstruction{'OR A, L', 1, true, none},
	CPUInstruction{'OR A, HL', 1, false, none},
	CPUInstruction{'OR A, A', 1, true, none},
	CPUInstruction{'CP A, B', 1, true, none},
	CPUInstruction{'CP A, C', 1, true, none},
	CPUInstruction{'CP A, D', 1, true, none},
	CPUInstruction{'CP A, E', 1, true, none},
	CPUInstruction{'CP A, H', 1, true, none},
	CPUInstruction{'CP A, L', 1, true, none},
	CPUInstruction{'CP A, HL', 1, false, none},
	CPUInstruction{'CP A, A', 1, true, none},
	CPUInstruction{'RET NZ', 1, true, none},
	CPUInstruction{'POP BC', 1, true, none},
	CPUInstruction{'JP NZ, a16', 3, true, none},
	CPUInstruction{'JP a16', 3, true, inst_jp_a16},
	CPUInstruction{'CALL NZ, a16', 3, true, none},
	CPUInstruction{'PUSH BC', 1, true, none},
	CPUInstruction{'ADD A, n8', 2, true, none},
	CPUInstruction{'RST \$00', 1, true, none},
	CPUInstruction{'RET Z', 1, true, none},
	CPUInstruction{'RET', 1, true, none},
	CPUInstruction{'JP Z, a16', 3, true, none},
	CPUInstruction{'PREFIX', 1, true, none},
	CPUInstruction{'CALL Z, a16', 3, true, none},
	CPUInstruction{'CALL a16', 3, true, none},
	CPUInstruction{'ADC A, n8', 2, true, none},
	CPUInstruction{'RST \$08', 1, true, none},
	CPUInstruction{'RET NC', 1, true, none},
	CPUInstruction{'POP DE', 1, true, none},
	CPUInstruction{'JP NC, a16', 3, true, none},
	CPUInstruction{'ILLEGAL_D3', 1, true, none},
	CPUInstruction{'CALL NC, a16', 3, true, none},
	CPUInstruction{'PUSH DE', 1, true, none},
	CPUInstruction{'SUB A, n8', 2, true, none},
	CPUInstruction{'RST \$10', 1, true, none},
	CPUInstruction{'RET C', 1, true, none},
	CPUInstruction{'RETI', 1, true, none},
	CPUInstruction{'JP C, a16', 3, true, none},
	CPUInstruction{'ILLEGAL_DB', 1, true, none},
	CPUInstruction{'CALL C, a16', 3, true, none},
	CPUInstruction{'ILLEGAL_DD', 1, true, none},
	CPUInstruction{'SBC A, n8', 2, true, none},
	CPUInstruction{'RST \$18', 1, true, none},
	CPUInstruction{'LDH a8, A', 2, false, none},
	CPUInstruction{'POP HL', 1, true, none},
	CPUInstruction{'LDH C, A', 1, false, none},
	CPUInstruction{'ILLEGAL_E3', 1, true, none},
	CPUInstruction{'ILLEGAL_E4', 1, true, none},
	CPUInstruction{'PUSH HL', 1, true, none},
	CPUInstruction{'AND A, n8', 2, true, none},
	CPUInstruction{'RST \$20', 1, true, none},
	CPUInstruction{'ADD SP, e8', 2, true, none},
	CPUInstruction{'JP HL', 1, true, none},
	CPUInstruction{'LD a16, A', 3, false, none},
	CPUInstruction{'ILLEGAL_EB', 1, true, none},
	CPUInstruction{'ILLEGAL_EC', 1, true, none},
	CPUInstruction{'ILLEGAL_ED', 1, true, none},
	CPUInstruction{'XOR A, n8', 2, true, none},
	CPUInstruction{'RST \$28', 1, true, none},
	CPUInstruction{'LDH A, a8', 2, false, none},
	CPUInstruction{'POP AF', 1, true, none},
	CPUInstruction{'LDH A, C', 1, false, none},
	CPUInstruction{'DI', 1, false, none},
	CPUInstruction{'ILLEGAL_F4', 1, true, none},
	CPUInstruction{'PUSH AF', 1, true, none},
	CPUInstruction{'OR A, n8', 2, true, none},
	CPUInstruction{'RST \$30', 1, true, none},
	CPUInstruction{'LD HL, SP, e8', 2, true, none},
	CPUInstruction{'LD SP, HL', 1, true, none},
	CPUInstruction{'LD A, a16', 3, true, none},
	CPUInstruction{'EI', 1, true, none},
	CPUInstruction{'ILLEGAL_FC', 1, true, none},
	CPUInstruction{'ILLEGAL_FD', 1, true, none},
	CPUInstruction{'CP A, n8', 2, true, none},
	CPUInstruction{'RST \$38', 1, true, none},
]

fn inst(op u8) CPUInstruction {
	return insts_unprefixed[op]
}

fn inst_prefixed(op u8) CPUInstruction {
	unsafe {
		static prefixed := []CPUInstruction{}
	}

	dump('TODO: inst_prefixed')
	return CPUInstruction{}
}
